### ISSUE TITLE
Using LE in the wasm-bindings breaks the signature in zksync

### ISSUE THREAD

**Issue by simon-jentzsch** [matter-labs/schnorr-musig#6]
First, thanks for this create schnorr impl. I use this and integrated it into a testproject where I want to sign with a schnorr musig signature with 2 keys a zksync transaction.
But even though the verify-function always verified correctly, the zksync-server never accepted my signature, because of an invalid s value.
After hours of debugging I found the reason:
In the wasm-bindings you use 
```rs
        signature
            .s
            .into_repr()
            .write_be(&mut encoded_sig[crate::decoder::STANDARD_ENCODING_LENGTH..])
            .map_err(|_| MusigABIError::EncodingError)?;
```            

while the `sign_musig` function encodes them with `write_le`.
After changing it to `write_le` (also in the verifier) it was able to verify the signature.

Is there a special reason for using `write_be`?

**Comment by saitima** [comment]
Hi @simon-jentzsch!

You may want to switch to "dev" branch which contains corresponding [commits](https://github.com/matter-labs/schnorr-musig/commit/387bc21f14ab6efbf0c6f951c53af5487b062962) for this issue.  They will be merged into master soon but you can use it until then. Feel free to reach for further questions!

**Comment by ly0va** [comment]
`dev` is merged now with correct implementation, so I'm closing this
